### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by anneka-le** [freebites/product#18]
## Task Description

We want to send notifications to users either when there is a new posting, another user replies to their comment, or another user comments on their own post. To do this, we will need to utilize an API (which will do a lot of the heavy lifting). 

## Acceptance Criteria

- [x] Is a notification sent to the user when there is a new post created?
- [ ] Is a notification sent to the user when another user replies to their comment?
- [ ] Is a notification sent to the user when another user comments on their post?

## Subtask Breakdown

- Create push notifications. 

## Recommended Approach

- Consider looking through this [Expo notifications documentation](https://docs.expo.dev/versions/latest/sdk/notifications/).
- Do some research before jumping in. I have never implemented push notifications before, but I found an [article](https://www.smashingmagazine.com/2022/04/guide-push-notifications-developers/) that may be a good place to start. 
- Consider which API would be the best. We are already using Firebase for some backend functions, so that may be an ideal choice, but there are other APIs that could make implementation easier or look better. Keep in mind cost (although I think TCU could pay for it?).
