### ISSUE TITLE
Information Modal

### ISSUE THREAD

**Issue by anneka-le** [freebites/product#19]
## Task Description

We want to create an information modal on food & dietary restrictions. Refer to the Figma to get a sense of what is needed for the modal.

<img width="348" alt="Screenshot 2024-03-31 at 16 41 26" src="https://github.com/freebites/product/assets/67713268/782405ab-801c-4c93-8394-cecf36f1114b">

Because we will be using this modal in various parts of the application, be sure to make this modal a component. 

## Acceptance Criteria

- [ ] When the user clicks on the information button on a post, does the modal appear to provide them the food and dietary information?
- [ ] When the user clicks out of the modal, does it go away on click?
- [ ] Does the "I got it!" button make the modal go away on click?

## Subtask Breakdown

- Create the food types & dietary restrictions information modal. 
- On a user's post, create an information button that on click triggers the modal to appear. 

## Recommended Approach

- Begin by creating the modal component & populate it with the information all found in the Figma.
- Test that the "I got it!" button makes the modal disappear.
- On the post page, create an information button (as shown in the Figma) that on click triggers the modal to appear.
