### ISSUE TITLE
Styling: Home Page & Login/Sign-Up

### ISSUE THREAD

**Issue by anneka-le** [freebites/product#20]
## Task Description

Style the Home Page and the Login/Sign-Up pages as per the [Figma](https://www.figma.com/file/pxgrEsnOJneqsaWWeEnQoY/FreeBites?type=design&node-id=2904%3A12611&mode=design&t=ASnzrFFtsl0cB5Ux-1).

## Acceptance Criteria

- [ ] Is the home page styled as per the Figma?
- [ ] Is the login page styled as per the Figma?
- [ ] Is the sign up page styled as per the Figma?

## Subtask Breakdown

- Style the pages.

**Comment by sristii** [comment]
Updated! See #25 :D
