### ISSUE TITLE
Profile Functionality

### ISSUE THREAD

**Issue by anneka-le** [freebites/product#21]
## Task Description

Now that the profile page is styled, we will implement the functionality of it. This includes updating the profile image, changing passwords, pronouns, etc.. When the user goes to their profile page, they should be able to edit their information. Once they edit their information, there should be a checkmark in the top right that allows them to save their changes.

## Acceptance Criteria

- [ ] #23
- [ ] Is the user able to update their own profile image?
- [ ] Is the user able to change their password based on the criteria set when signing up?
- [ ] Is the user able to update their pronouns?

## Subtask Breakdown

- Implement the functionality of the profile page. This includes updating the form and the profile image.

## Recommended Approach

- Begin with the form and test that the edits are being updated in the database as well as displaying on the frontend.
- Once the form is complete, move on to the image. You may have to do some poking around in Firebase in order to update this.

**Comment by sristii** [comment]
Updated for summer sprint :))
