### ISSUE TITLE
Styling: Onboarding Pages & Post Cards

### ISSUE THREAD

**Issue by sristii** [freebites/product#25]
## 📝 Task Description 

Style the Welcome, Login/Sign-Up pages, and post cards according to the [Figma](https://www.figma.com/file/pxgrEsnOJneqsaWWeEnQoY/FreeBites?type=design&node-id=2904%3A12611&mode=design&t=ASnzrFFtsl0cB5Ux-1).

## ✅ Acceptance Criteria 

- [x] Is the welcome page styled as per the Figma?
- [x] Is the login page styled as per the Figma?
- [x] Is the sign-up page styled as per the Figma?
- [x] Are the post cards styled as per the Figma?
- [x] Are the modals (pop-ups) made as per the Figma?

## 🔍  Subtask Breakdown

- Style the welcome page
  - FreeBites logo and text
  - Login/signup buttons & touch effects
  - Overall spacing & sizing changes
- Style the login/signup pages
   - Logo, page title
   - Email / Password fields
   - Checkbox & text
   - Get Started/Login Button
   - Don’t have an account? Sign Up or Have an account? Login 
- Posts/Card changes (component --> HomePost.tsx)
   - Overall changes to the look/style
    - ‼️ Posts made by the user should have a delete button → when pressed it leads to a “Are you sure you want to delete?” modal (style this too please!)

** As you work, ensure to implement any touch (hover) effects for clickable objects **

## 💫  Recommended Approach

A suggestion is to start with the Welcome page → Login/Signup → Post Cards → Modals, as that's in increasing level of difficulty. Since this ticket also consolidates a bunch of pages – feel free to make separate PRs as you finish each page~

Pulling up the Figma and utilizing Dev Mode & Preview Mode helps get a good sense of what the app should look like for the user, aiding you guys as you code! This is particularly important for seeing the various effects buttons should have when a user clicks it, or to sanity check that your implementation matches the Figma.

Moreover, you’ll notice that some of the code will be repetitive so reuse it (++ points for abstraction yay!!) 

## ✨ Styling Resources ✨

- [How to CSS](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
- [Clarence's Styling Presentation](https://docs.google.com/presentation/d/10k0kGCUdR3twBIv9yDJ0hOQZCDFyoy99SGMMBguShFg/edit#slide=id.g24e07eed7b0_1_75)
