### ISSUE TITLE
Drafts

### ISSUE THREAD

**Issue by sristii** [freebites/product#26]
## 📝 Task Description

To enhance user experience, we will implement the functionality for users to create drafts and save them locally on their devices. This will allow users to start creating content and save their progress without publishing immediately. Users should be able to access and edit their drafts once saved. **Reference the [Figma](https://www.figma.com/file/pxgrEsnOJneqsaWWeEnQoY/FreeBites?type=design&node-id=2904%3A12611&mode=design&t=ASnzrFFtsl0cB5Ux-1) for draft flows and how it should look!**

## ✅ Acceptance Criteria

- [ ] Is the user able to save an incomplete post as a draft?
- [ ] Is the draft saved locally?
  - [ ] Is the draft accessible from any device once saved?
  - [ ] Is the user-inputted content (title, location, etc..) still viewable?
- [ ] Can the user edit their draft?
  - [ ] Can they update the content?
- [ ] Can the user delete their draft?
- [ ] Can the user post their draft?
- [ ] Can the user save their draft as a draft? 

## 🔍 Subtask Breakdown

- Draft Creation
  - When a user goes to exit the post creation page (three dots in upper-right-hand corner), they should be prompted to turn the incomplete post into a draft that will then save the draft 
- Local Storage
  - If a user chooses to save a post as a draft, save it LOCALLY
- Draft Editing
  - Bringing the user back to the initial “post” flow when they enter their draft once again
- Draft Deletion
  - Providing an option to delete drafts

## 💫 Recommended Approach

1. Begin with building the functionality to save an incomplete post as a draft (i.e. not a post, and not on the database). Have the draft stored locally.

2. Then, pull the drafts from local storage + display them on the "Drafts" page.

3. Once drafts can be viewed by the user in the proper place “Drafts” under Account, implement the functionality that brings them back to the “Posting” flow when the user goes back to edit the Draft.

4. Then, implement the delete functionality. (Deleting a selected item from local storage)

***Note: The component for the draft cards is the same as the post ones! This component is "HomePost.tsx"***

## ✨ Resources ✨

- [How to Store Data Locally in React Native Expo](https://www.freecodecamp.org/news/how-to-store-data-locally-in-react-native-expo/#:~:text=use%20them%20effectively.-,setItem(),the%20data%20to%20be%20stored.)
