### ISSUE TITLE
Profile Functionality

### ISSUE THREAD

**Issue by sristii** [freebites/product#28]
## 📝 Task Description

Now that the profile page is styled, we will implement the functionality of it. This includes updating the profile image, username, pronouns, etc. Users should be able to edit their information when they go to their profile page. Once they edit their information, the checkmark in the top right allows them to save their changes. **Reference the [Figma](https://www.figma.com/file/pxgrEsnOJneqsaWWeEnQoY/FreeBites?type=design&node-id=2904%3A12611&mode=design&t=ASnzrFFtsl0cB5Ux-1) for Profile flows and how it should look!**

## ✅ Acceptance Criteria

- [x] Is the user able to edit their profile information?
  - [x] Is the user able to update their Name?
  - [x] Is the user able to update their username?
  - [x] Is the user able to update their pronouns?
  - [x] Can they save changes by pressing the check mark?
- [x] Is the user able to update their profile image?
  - [x] Can they choose an image from their album?
  - [x] Can they take a photo with their camera?
  - [x] Can they remove their photo?

## 🔍 Subtask Breakdown

-  Updating the form (with user details)
   - Ensure saved changes to the form are displayed on the front end
- Profile image updating

## 💫 Recommended Approach

1. Begin with the form and test that the edits are being updated in the database and displayed on the front end.

2. Once the form is complete, begin working on the image. You may have to do some poking around in Firebase in order to update this. Take a look at the way images are implemented for posts too!

## ✨ Resources ✨

- It may be helpful to reference the past issue/PR for profiles! [Issue](#10) [PR](#14)
