### ISSUE TITLE
Async Storage & App State

### ISSUE THREAD

**Issue by sristii** [freebites/product#31]
## 📝 Task Description

To enhance user experience and manage the application state effectively, we will implement the functionality for users to save settings, app state, and other necessary data using Async Storage. This will give users a seamless experience with their preferences and states preserved across sessions. 

## ✅ Acceptance Criteria

- [x] Are user settings and location saved locally?
  - [x] Are the settings accessible from any session once saved?
- [x] Can the user update their settings and have it be saved?
- [x] Is the app state saved?
- [x] Is the app state restored upon app restart?

## 🔍 Subtask Breakdown

- Settings & Local Storage
  - Use Async Storage to save user settings/location locally
  - Retrieve and apply settings upon app launch
  - You can modify the settings page with “dummy settings” for testing purposes
- App State Management 
  - Dive into managing the global app state
  - Ensure state updates correctly and is persistent across session

***‼️ Note: Throughout this task, keep the storage info in one place, if possible! -appContext is where stuff is currently stored ‼️***

## 💫 Recommended Approach

1. Implement Async Storage:
   - Integrate Async Storage to save user settings locally
   - Ensure settings are retrieved and applied on app launch

2. State and Settings Restoration:
   - Implement functionality to restore app state upon app reopening
   - Ensure the state and settings are consistently applied across sessions

**If there are functionalities that you need in Async Storage that aren’t there → Look into Redux and Redux persist.**

## ✨ Resources ✨
   - [How to Store Data Locally in React Native Expo](https://www.freecodecamp.org/news/how-to-store-data-locally-in-react-native-expo/#:~:text=use%20them%20effectively.-,setItem(),the%20data%20to%20be%20stored.)
   - [Async Storage Documentation](https://react-native-async-storage.github.io/async-storage/docs/install/)
   - [Redux Documentation](https://redux.js.org/introduction/getting-started) (if needed)
