### ISSUE TITLE
Frontend Brush-ups & Loading Skeletons

### ISSUE THREAD

**Issue by sristii** [freebites/product#36]
## 📝 Task Description 

Minor styling fixes and implementing loading pages according to the [Figma](https://www.figma.com/file/pxgrEsnOJneqsaWWeEnQoY/FreeBites?type=design&node-id=2904%3A12611&mode=design&t=ASnzrFFtsl0cB5Ux-1).

## ✅ Acceptance Criteria 

- [x] Do the post cards grab the information?
- [x] Is the tab bar styled as per the Figma?
- [x] Are the loading skeletons made as per the Figma?
- [x] Are PNGs turned into SVGs?

## 🔍  Subtask Breakdown

- Pull info onto the post cards
- Style the tab bar
   - Spacing
   - Icons shouldn't be PNGs → Make svgs or import icons
- Style the loading skeletons
  - View “Edge Cases” in the Figma

** As you work, ensure to implement any touch (hover) effects for clickable objects **

## 💫  Recommended Approach

Same drill as the last sprint!! Work through the checklist in order, as that's in increasing level of difficulty. 

A reminder that pulling up the Figma and utilizing Dev Mode & Preview Mode is your biggest help as you code! 

## ✨ Styling Resources ✨
- [How to CSS](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
- [Clarence's Styling Presentation](https://docs.google.com/presentation/d/10k0kGCUdR3twBIv9yDJ0hOQZCDFyoy99SGMMBguShFg/edit#slide=id.g24e07eed7b0_1_75)
- [Skeleton Screens for Better Loading in React](https://medium.com/whitespectre/skeleton-screens-for-better-loading-in-react-16f850596b24)
- [cool skeleton thing](https://www.youtube.com/watch?v=zM3l9jpt5PU&ab_channel=UnsureProgrammer)
