### ISSUE TITLE
View Other User's Profiles

### ISSUE THREAD

**Issue by sristii** [freebites/product#37]
## 📝 Task Description

This ticket focuses on implementing users' functionality to view other people's profiles within the application. This feature will allow users to see the profiles of other users, including their profile picture, pronouns, username, and posts. View the [Figma](https://www.figma.com/file/pxgrEsnOJneqsaWWeEnQoY/FreeBites?type=design&node-id=2904%3A12611&mode=design&t=ASnzrFFtsl0cB5Ux-1).

## ✅ Acceptance Criteria

- [ ] **User Profile View**
  - [ ] Users can navigate to other users' profiles from various parts of the application by clicking their user icon.
  - [ ] Each user profile page should display the user's profile picture, pronouns, and username.
  - [ ] Ability to view the posts created by the profile owner.
- [ ] **Navigation**
  - [ ] Implement navigation to user profiles from posts and comment sections.
- [ ] **User Interaction**
  - [ ] Users should be able to interact with the content on the persons page (i.e. opening the post)

## 🔍 Subtask Breakdown

- **Profile Page**
  - Design and implement the layout for displaying user profiles.
  - Include sections for user bio, profile picture, and posts.
- **Navigation**
  - Implement navigation to user profiles from different parts of the application, such as posts or comments.
- **User Interaction**
  - Implement functionality for users to interact with the content on the profile page, such as liking or commenting on posts.

## 💫 Recommended Approach

1. **Design Profile Page:**
   - Create a design for the user pages, including layout and components.
   - Fetch and display the user's profile picture, pronouns, username, and posts.
2. **Navigation to Profiles:**
  - Implement navigation to user profiles from different parts of the application, such as posts or comments.

## ✨ Resources ✨

- [React Navigation Documentation](https://reactnavigation.org/docs/getting-started)
- [React Native Elements Documentation](https://reactnativeelements.com/docs/overview)
