### ISSUE TITLE
Settings Implementation

### ISSUE THREAD

**Issue by sristii** [freebites/product#46]
## 📝 Task Description

Implement the settings page, including both the front-end design and the functionality for various settings sections: Account, Notifications, Privacy, Help, and About.

## ✅ Acceptance Criteria

- [x] Is the settings page styled as per the Figma?
- [x] Are the Account settings functional and styled as per the Figma?
- [ ] Are the Notifications settings functional and styled as per the Figma?
- [x] Are the Privacy settings functional and styled as per the Figma?
- [x] Are the Help & About sections functional and styled as per the Figma?
- [x] Are the dropdowns for each settings section working correctly?

## 🔍 Subtask Breakdown

- Style the settings page according to the Figma design
  - Overall layout
  - Spacing
  - Typography
- Ensure dropdowns for each settings section are functional
  - Smooth opening and closing
  - Proper touch (hover) effects for clickable objects

## 💫 Recommended Approach

Refer to the Figma design for exact styling and layout. Use Dev Mode & Preview Mode in Figma for assistance while coding. For the Account updating, utilize the code provided by Jet/Owen.

## ✨ Resources ✨
- [How to CSS](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
- [Clarence's Styling Presentation](https://docs.google.com/presentation/d/10k0kGCUdR3twBIv9yDJ0hOQZCDFyoy99SGMMBguShFg/edit#slide=id.g24e07eed7b0_1_75)
- [Dropdowns in React](https://reactjs.org/docs/forms.html#the-select-tag)

Ensure all implemented sections match the design and functionality requirements in the Figma.

Also, a lot of the settings themselves have already been implemented, but you'd need to turn it on or off!
