### ISSUE TITLE
Post Updates – Reporting & Sharing

### ISSUE THREAD

**Issue by sristii** [freebites/product#47]
## 📝 Task Description

Implement Post Updates – Reporting & Sharing, and ensure that posts match the design specifications in the Figma.

## ✅ Acceptance Criteria

- [ ] Is the post styled as per the Figma?
- [ ] Is the reporting functionality implemented and working correctly?
- [ ] Is the sharing functionality implemented and working correctly?
- [ ] Are all touch (hover) effects for clickable objects implemented?

## 🔍 Subtask Breakdown

- Style the post to match the Figma design (this should be kinda done -- but just ensure that it matches properly)
  - Overall layout
  - Spacing
  - Typography
  - Media (images, videos) placement
- Implement the reporting functionality
  - Front end design
  - Backend integration for reporting a post
  - Confirmation message or modal after reporting
- Implement the sharing functionality
  - Front end design
  - Options for sharing (e.g., social media, direct link)
  - Confirmation message or modal after sharing
- Ensure all clickable objects have touch (hover) effects

## 💫 Recommended Approach

Refer to the Figma design for exact styling and layout. Use Dev Mode & Preview Mode in Figma for assistance while coding.

✨ Resources for Implementation ✨
- [How to CSS](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
- [Clarence's Styling Presentation](https://docs.google.com/presentation/d/10k0kGCUdR3twBIv9yDJ0hOQZCDFyoy99SGMMBguShFg/edit#slide=id.g24e07eed7b0_1_75)
- [Sharing on Expo](https://docs.expo.dev/versions/latest/sdk/sharing/)

Ensure all implemented features and styles match the design and functionality requirements in the Figma.
