### ISSUE TITLE
Styling: Cleanup & Forgot/Change Password

### ISSUE THREAD

**Issue by sristii** [freebites/product#66]
## 📝 Task Description 

Front-end implementation of Forgot/Change Password + Styling fixes (Onboarding Cleanup)
View the [Figma](https://www.figma.com/file/pxgrEsnOJneqsaWWeEnQoY/FreeBites?type=design&node-id=2904%3A12611&mode=design&t=ASnzrFFtsl0cB5Ux-1).

## ✅ Acceptance Criteria 

- [x] Start page logo not cut off?
- [x] Are the onboarding pages fixed while maintaining functionality?
- [x] Are the checkboxes aligned and color-matched to the Figma?
- [x] Are the "Forgot Password?" page and "Update Password" pages styled according to the Figma?
- [x] Is there a **functional** back button on the "Forgot Password?" page?

## 🔍  Subtask Breakdown

**‼️ Task 1: Welcome Page Logo**

<img src="https://github.com/user-attachments/assets/173f0eae-1753-4281-8808-3a7ac23c9f95" alt="Description" width="300">

- If you view the Figma you'll see that the logo is a bit more vertically centered, with login and sign-up buttons below. Also, the Freebites text logo is a bit cut off!

**‼️ Task 2 & 3**

https://github.com/user-attachments/assets/1869cb3d-c3f2-4015-8fab-9547eb86f1f7

- For the certain pages there is the ability to scroll - but we'd like to make that fixed (unless the content overflows)! You'll notice that when you scroll down to much the bottom cuts off any components which looks a bit off!

- Also, the "Remember Me" checkbox should match the Figma! (Check: Border and filler color of the box, as well as it being aligned with the text boxes ontop!!)

**‼️ Task 4**
- The "Forgot Password" and "Change Password" pages are not styled, so please implement the front-end. :-)

## 💫  Recommended Approach

- Work through the checklist in order, as that's in increasing level of difficulty.  Re-use old code and components since many of these pages follow the same design we already have done!

- A reminder that pulling up the Figma and utilizing Dev Mode & Preview Mode is your biggest help as you code! 

## ✨ Styling Resources ✨
- [How to CSS](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
- [Clarence's Styling Presentation](https://docs.google.com/presentation/d/10k0kGCUdR3twBIv9yDJ0hOQZCDFyoy99SGMMBguShFg/edit#slide=id.g24e07eed7b0_1_75)
- [React Native Animated Fade In Fade Out Effect](https://www.geeksforgeeks.org/react-native-animated-fade-in-fade-out-effect/)
