### ISSUE TITLE
Admin View

### ISSUE THREAD

**Issue by sristii** [freebites/product#67]
## 📝 Task Description 

To ensure a smooth user experience, we've decided to implement an admin interface where users designated as admins can review any reported content. Since you guys worked on the reports this will build off of it! It is def a lengthy ticket so do communicate whenever you guys need further clarification!
View the [Admin Section in Figma](https://www.figma.com/design/pxgrEsnOJneqsaWWeEnQoY/FreeBites?node-id=5934-8368&t=fl9QYpo0e8MjRRaO-4).

## ✅ Acceptance Criteria 

- [ ] Can **only** those with the admin password view the reported posts?
- [x] Can the posts be archived or reported?
- [ ] Is the username and profile picture of the reporter displayed, along with the reasoning of the report?
- [x] Does the styling match the Figma?
- [ ] Can admins exit the admin view at the top-right-hand corner?

## 🔍  Subtask Breakdown

**‼️ Task 1: Creating a Section of the app only accessed via admin password**
**‼️ Task 2: Display the reported posts under the reported section**
**‼️ Task 3: Pull information from the report like the username, reasoning, etc...**
**‼️ Task 4: Functionality to remove posts for all users**

## 💫  Recommended Approach

- Re-use old code and components since many of these pages follow the same design we already have done! Reach out for what to set the admin password to (but for testing you can make a dummy one!).

- A reminder that pulling up the Figma and utilizing Dev Mode & Preview Mode is your biggest help as you code! 

## ✨ Styling Resources ✨
- [How to CSS](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
- [Clarence's Styling Presentation](https://docs.google.com/presentation/d/10k0kGCUdR3twBIv9yDJ0hOQZCDFyoy99SGMMBguShFg/edit#slide=id.g24e07eed7b0_1_75)

p.s. I'll add more info to this issue as it comes in :)

**Comment by sristii** [comment]
**Note:** We're also still figuring out how the design should look, so when you guys get started please check in with us! We want to make sure y'all are updated + tackle the ticket in the most optimal way!
