### ISSUE TITLE
Bug Fixes (Posts + Profile)

### ISSUE THREAD

**Issue by sristii** [freebites/product#68]
## 📝 Task Description 

Hey guys! This ticket includes bug-correcting tasks across various sections of the app, mainly dealing with posts and the profile page!
View the [Figma](https://www.figma.com/design/pxgrEsnOJneqsaWWeEnQoY/FreeBites?node-id=5934-8368&t=fl9QYpo0e8MjRRaO-4).

## ✅ Acceptance Criteria 

- [x] Does the post card match the Figma **exactly**?
- [x] Does the post flow match the Figma **exactly**?
- [x] Does clicking check when updating your profile route back to the default profile page?

## 🔍  Subtask Breakdown

**‼️ Task 1: Post Card Tweaks**

- No leaves anymore
- Time needs to pull the actual time info 
- Slightly bigger user display
- Bottom shadow rounded -> Should outline the entire card

<img width="679" alt="Screenshot 2024-08-07 at 1 09 17 AM" src="https://github.com/user-attachments/assets/08701ffa-b8b0-418d-95bc-de6c41ffdbc1">
<br>

**‼️ Task 2: Post Flow Updates**

- Word counter starts at 4 - should be 0
- Progress bar needs Freebites logo

View this section in [Figma](https://www.figma.com/design/pxgrEsnOJneqsaWWeEnQoY/FreeBites?node-id=3067-15838&t=9dM40xRUWmjBPmyy-4)

**‼️ Task 3: Profile: Clicking check when updating profile takes you back to profile page**

- ^ pretty much the title loll

**‼️ Task 4: Trash Can**

- trash can is in a goofy place, pls fix

## 💫  Recommended Approach

- Bunch of tasks together so if anything needs further clarification do not be afraid to reach out!

- A reminder that pulling up the Figma and utilizing Dev Mode & Preview Mode is your biggest help as you code! 

## ✨ Styling Resources ✨
- [How to CSS](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
- [Clarence's Styling Presentation](https://docs.google.com/presentation/d/10k0kGCUdR3twBIv9yDJ0hOQZCDFyoy99SGMMBguShFg/edit#slide=id.g24e07eed7b0_1_75)
