### ISSUE TITLE
Comment Replies

### ISSUE THREAD

**Issue by sristii** [freebites/product#71]
## 📝 Task Description 

Hiii guys!! This will be a back-end ticket!! It is pretty different from what you guys have been working with, so reach out with anyyy questions/concerns! You may end up needing to read a good amount of documentation. BUT YALL R SMART AND TALENTED SO U GOT THIS
View the [Figma](https://www.figma.com/design/pxgrEsnOJneqsaWWeEnQoY/FreeBites?node-id=5934-8368&t=fl9QYpo0e8MjRRaO-4). 

## ✅ Acceptance Criteria 

- [ ] Can users reply to comments?
- [ ] Will the other person be notified when they get a comment reply?
- [ ] (added) when no comment is made, the button should be greyed out and disabled

## 🔍  Subtask Breakdown

Look into the way the comments are implemented, then implement a reply button. When a user clicks on this reply button, it should populate the comment field with an @ of the person they are replying to. For now, we don't have to worry about making them collapsable (ex. "see 4 replies") but can just have the replies be posted as other comments. Then try to figure out how to get the person who is tagged to receive a notification!

## ✨ Resources ✨
- View PR #15 , this has all of the code pertaining to comments
- I'll add more resources as I find them!
